### ISSUE TITLE
[bug]: Unable to initialize the project using vite

### ISSUE THREAD

**Issue by karananeja** [scriptkavi/hooks#2]
### Describe the bug

Unable to initialize the project using vite, the hooks and utils folder is not created under src folder as expected

### Affected hooks/hook

Initialization using vite

### How to reproduce

1. Create project
2. Edit tsconfig.json file
3. Update vite.config.ts
4. Run the CLI
5. Configure hooks.json

Now check the folder structure generated

### System Info

```bash
NA
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by sunnynk19** [comment]
Hi @karananeja , I will look into it

**Comment by sunnynk19** [comment]
@karananeja, It is fixed. I have updated the document. You can try it again.
